[base]
default          = none
unknown-token    = #ed1515
commandseparator = #f67400,bold
redirection      = #f67400,bold
here-string-tri  = #f67400
here-string-text = #95a5a6
here-string-var  = #1abc9c,bg:#31363b
exec-descriptor  = #f67400,bold
comment          = #7f8c8d,bold
correct-subtle   = #1cdc9a
incorrect-subtle = #ed1515
subtle-separator = #11d116
subtle-bg        = bg:#31363b
secondary        = free
; recursive-base   =

[command-point]
reserved-word     = #9b59b6,bold
subcommand        = #fdbc4b
alias             = #1abc9c,bold
suffix-alias      = #1abc9c,bold
global-alias      = #1abc9c,bold
builtin           = #3daee9
function          = #11d116,bold
command           = #1d99f3,bold
precommand        = #f67400,bold
hashed-command    = #1d99f3,bold
single-sq-bracket = #11d116
double-sq-bracket = #11d116
double-paren      = #f67400

[paths]
path          = #9b59b6
pathseparator = #eff0f1
path-to-dir   = #9b59b6,underline
globbing      = #1d99f3,bold
globbing-ext  = #8e44ad

[brackets]
paired-bracket  = bg:#7f8c8d
bracket-level-1 = #11d116,bold
bracket-level-2 = #f67400,bold
bracket-level-3 = #1abc9c,bold

[arguments]
single-hyphen-option   = #7f8c8d
double-hyphen-option   = #7f8c8d
back-quoted-argument   = #1cdc9a
single-quoted-argument = #1cdc9a
double-quoted-argument = #1cdc9a
dollar-quoted-argument = #1cdc9a

[in-string]
back-dollar-quoted-argument           = #1abc9c
back-or-dollar-double-quoted-argument = #1abc9c

[other]
variable             = #1cdc9a
assign               = #9b59b6
assign-array-bracket = #11d116
history-expansion    = #1d99f3,bold

[math]
mathvar = #3daee9,bold
mathnum = #9b59b6
matherr = #ed1515,bold

[for-loop]
forvar  = #1d99f3
fornum  = #9b59b6
foroper = #f67400
forsep  = #f67400,bold

[case]
case-input       = #11d116
case-parentheses = #f67400
case-condition   = bg:#1d99f3
