[base]
default          = none
unknown-token    = #ff5fab,bold
commandseparator = yellow,bold
redirection      = yellow,bold
here-string-tri  = yellow
here-string-text = 18
here-string-var  = cyan,bg:18
exec-descriptor  = yellow,bold
comment          = black,bold
correct-subtle   = 12
incorrect-subtle = red
subtle-separator = green
subtle-bg        = bg:18
secondary        = free
; recursive-base   =

[command-point]
reserved-word  = magenta,bold
subcommand     = yellow
alias          = cyan,bold
suffix-alias   = cyan,bold
global-alias   = cyan,bold
builtin        = yellow
function       = green,bold
command        = blue,bold
precommand     = red,bold
hashed-command = blue,bold
single-sq-bracket = green
double-sq-bracket = green
double-paren   = yellow

[paths]
path          = magenta
pathseparator = white
path-to-dir   = magenta,underline
globbing      = blue,bold
globbing-ext  = 13

[brackets]
paired-bracket = bg:blue
bracket-level-1 = green,bold
bracket-level-2 = yellow,bold
bracket-level-3 = cyan,bold

[arguments]
single-hyphen-option   = 244
double-hyphen-option   = 244
back-quoted-argument   = green
single-quoted-argument = green
double-quoted-argument = green
dollar-quoted-argument = green

[in-string]
back-dollar-quoted-argument           = cyan
back-or-dollar-double-quoted-argument = cyan

[other]
variable             = 113
assign               = #C678DD
assign-array-bracket = green
history-expansion    = blue,bold

[math]
mathvar = blue,bold
mathnum = magenta
matherr = red

[for-loop]
forvar = #D19A66
fornum = magenta
foroper = yellow
forsep = yellow,bold

[case]
case-input       = green
case-parentheses = yellow
case-condition   = bg:blue
